//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachHang()
        {
            this.thanhToans = new HashSet<thanhToan>();
        }
    
        public int Ma_kh { get; set; }
        public string Ho_ten { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> Gioi_tinh { get; set; }
        public Nullable<int> Lan_mua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thanhToan> thanhToans { get; set; }
    }
}
