//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanhToan
    {
        public int Ma_kh { get; set; }
        public int Ma_sp { get; set; }
        public string Ho_ten { get; set; }
        public string SDT { get; set; }
        public Nullable<int> So_luong { get; set; }
        public Nullable<int> Gia_tien { get; set; }
        public Nullable<int> Tien_khach_tra { get; set; }
    
        public virtual doChoi doChoi { get; set; }
        public virtual khachHang khachHang { get; set; }
    }
}
